[package]
name = "game_of_life"
version = "0.1.0"
edition = "2021"

[lib]
name = "board_crate"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
rltk = { version = "0.8.0" }